---
- name: Ensure kubectl is installed
  command: which kubectl
  register: kubectl_check
  ignore_errors: true

- name: Install kubectl if not present
  command: curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl" &&
           chmod +x kubectl &&
           mv kubectl /usr/local/bin/kubectl
  when: kubectl_check.rc != 0

- name: Create namespace for ArgoCD
  command: kubectl create namespace argocd
  environment:
    KUBECONFIG: "{{ kubeconfig_path }}"
  ignore_errors: true

- name: Apply ArgoCD manifests
  command: >
    kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
  environment:
    KUBECONFIG: "{{ kubeconfig_path }}"
