---
- name: Add ArgoCD Helm repository
  kubernetes.core.helm_repository:
    name: argo
    repo_url: https://argoproj.github.io/argo-helm

- name: Install ArgoCD
  kubernetes.core.helm:
    name: argocd
    chart_ref: argo/argo-cd
    release_namespace: argocd
    create_namespace: true
    values:
      server:
        extraArgs:
          - --insecure
      configs:
        secret:
          argocdServerAdminPassword: "{{ lookup('password', '/dev/null length=16 chars=ascii_letters,digits') | password_hash('bcrypt') }}"