---
- name: Add Prometheus community Helm repository
  kubernetes.core.helm_repository:
    name: prometheus-community
    repo_url: https://prometheus-community.github.io/helm-charts

- name: Install Kube-Prometheus Stack
  kubernetes.core.helm:
    name: prometheus
    chart_ref: prometheus-community/kube-prometheus-stack
    release_namespace: monitoring
    create_namespace: true
    values:
      grafana:
        enabled: true
      prometheusOperator:
        enabled: true
      prometheus:
        enabled: true
        serviceMonitor:
          enabled: true